export const SelectorMap = {
  ProjectsSlider: "[data-projects-slider]",
  ProjectSlider: "[data-project-slider]",
  TelMaskInput: "input[type=tel]",
  ContactsSlider: "[data-contacts-slider]",
  ContactsSidebar: "[data-contacts-sidebar]",
  ContactsSidebarCloseTrigger: "[data-contacts-sidebar-close]",
  ContactsMapMarkerTrigger: "[data-contacts-map-marker-trigger]",
  ContactsMap: "#contacts-map",
  ContactsSlidesWithMapMarker: "[data-contacts-map-marker]",
  FormControl: "[data-form-control]",
  FormControlMessage: "[data-form-control-message]",
  LazyLoadingImg: "[data-lazy-img]",
  LazyLoadingMap: "[data-lazy-map]",
} as const;
